model_name_or_path: naver-clova-ix/donut-base-finetuned-cord-v2
train_file: ./data/train.jsonl
validation_file: ./data/val.jsonl
output_dir: ./donut-invoice-model
num_train_epochs: 5
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
learning_rate: 5e-5
weight_decay: 0.01
warmup_steps: 200
max_seq_length: 384
image_size: [960, 720]
logging_dir: ./logs
logging_steps: 50
evaluation_strategy: steps
eval_steps: 100
save_steps: 200
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
gradient_accumulation_steps: 4
fp16: false
max_grad_norm: 1.0
dataloader_num_workers: 0
push_to_hub: false
report_to: none