model_name_or_path: naver-clova-ix/donut-base
train_file: ./data/train.jsonl
validation_file: ./data/val.jsonl
output_dir: ./donut-invoice-model
num_train_epochs: 10
per_device_train_batch_size: 4
per_device_eval_batch_size: 4
learning_rate: 5e-5
weight_decay: 0.01
warmup_steps: 500
max_seq_length: 512
logging_dir: ./logs
logging_steps: 100
evaluation_strategy: steps
eval_steps: 200
save_steps: 500
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
gradient_accumulation_steps: 2
fp16: true
push_to_hub: false
report_to: none
