model_name_or_path: naver-clova-ix/donut-base-finetuned-rvlcdip
train_file: ./data/train.jsonl
validation_file: ./data/val.jsonl
output_dir: ./donut-rvlcdip-invoice-model
num_train_epochs: 2
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
learning_rate: 3e-5
weight_decay: 0.01
warmup_steps: 100
max_seq_length: 256
max_target_length: 512
logging_dir: ./logs
logging_steps: 10
evaluation_strategy: steps
eval_steps: 50
save_steps: 100
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
gradient_accumulation_steps: 4
fp16: false
dataloader_num_workers: 1
push_to_hub: false
report_to: none