model_name_or_path: "naver-clova-ix/donut-base"
train_file: "./data/train.jsonl"
validation_file: "./data/val.jsonl"
output_dir: "./donut-invoice-model"
logging_dir: "./logs"
learning_rate: 1e-5
weight_decay: 0.01
num_train_epochs: 5
gradient_accumulation_steps: 4
use_preprocessed_features: true
features_dir: "./donut-invoice-model/features"