pretrained_model_name_or_path: "naver-clova-ix/donut-base-finetuned-docvqa"
dataset_path: "./data"
output_dir: "./output"
overwrite_output_dir: true

num_train_epochs: 3
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
learning_rate: 5e-5
weight_decay: 0.01

save_total_limit: 1
save_strategy: "epoch"
evaluation_strategy: "epoch"
logging_strategy: "steps"
logging_steps: 10

fp16: true

predict_with_generate: true
remove_unused_columns: false
seed: 42
